---
- hosts: web_server
  become: true
  tasks:
    - name: nginx installation
      yum: 
        name: nginx
        state: present
    - name: starting nginx
      service:
          name: nginx
          state: started
          enabled: true
