---
- hosts: all
  become: true
  tasks:
    - name: httpd installation
      yum: 
        name: httpd
        state: present
    - name: starting nginx
      service:
          name: httpd
          state: started
    - name: Static site
      copy: 
        src: index.html
        dest: /var/www/html/
