---
- hosts: all
  become: true
  tasks:
    - name: httpd installation
      yum: 
        name: httpd
        state: present
    - name: starting httpd
      service:
          name: httpd
          state: started
          enabled: true
